# options for analysis running
run:
  concurrency: 1
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-files:

issues:
  exclude-use-default: false

# CORRECTED output configuration
output:
  format: colored-line-number  # Keep singular 'format' for v1.50 compatibility
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable: # Changed from deprecated check-shadowing
      - atomicalign
      - printf
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: early-return
      - name: unused-parameter
  errcheck:
    check-type-assertions: true
    check-blank: false
  nakedret:
    max-func-lines: 30

linters:
  disable-all: true
  enable:
    - govet
    - revive       # Replaces golint
    - gosimple     # From original megacheck replacement
    - staticcheck  # From original megacheck replacement
    - unused
    - gofmt
    - goimports
    - errcheck
    - gocyclo
    - ineffassign
    - nakedret
    - unparam
  fast: false
