name: Update Emoji Data

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches:
      - feature/unicode-update-ci

jobs:
  update-emoji-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout gomoji
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gomoji-updater
        uses: actions/checkout@v4
        with:
          repository: forPelevin/gomoji-updater
          path: gomoji-updater

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.19"

      - name: Use local gomoji in updater
        run: |
          cd gomoji-updater
          go mod edit -replace github.com/forPelevin/gomoji=../
          go mod tidy

      - name: Generate emoji data
        run: |
          cd gomoji-updater
          go run ./cmd/updater/main.go --output ../data.go

      - name: Check for changes
        id: git-status
        run: |
          if git diff --quiet -- data.go; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.git-status.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-emoji-data
          title: "chore: update emoji data to latest Unicode version"
          commit-message: "chore: update emoji data to latest Unicode version"
          body: |
            Automated update of emoji data generated by [gomoji-updater](https://github.com/forPelevin/gomoji-updater).

            - Unicode source: https://unicode.org/Public/emoji/latest/
            - Generated on: ${{ github.event_name == 'schedule' && format('scheduled run {0}', github.run_id) || format('manual run {0}', github.run_id) }}
          labels: automated, dependencies
